# Generated by Django 4.0 on 2022-01-08 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_values', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingSearch',
            fields=[
                ('filter', models.TextField()),
                ('website', models.URLField()),
                ('scraping_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scraper.scrapingresult')),
            ],
        ),
    ]
