# Generated by Django 4.0 on 2022-01-08 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_rename_csv_values_scrapingresult_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingresult',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scrapingsearch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
