# Generated by Django 4.0 on 2022-01-08 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_scrapingresult_created_at_scrapingsearch_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingsearch',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrapingresult',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scrapingsearch',
            name='scraping_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scraper.scrapingresult'),
        ),
    ]
