# Generated by Django 4.0 on 2022-01-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_scrapingsearch_id_alter_scrapingresult_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
